name: Build and run
on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - run: sudo apt-get install libcxxopts-dev libeigen3-dev
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'default'
      - name: View help
        run: ./build/stdp --help
      - name: Test
        run: ctest --test-dir build
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: ./build/data/
