name: Build and run
on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -B build
      - run: cmake --build build
      - run: ./build/stdp --help
