name: Build and run
on: [push]

permissions:
  contents: read
  checks: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - run: sudo apt-get install libcli11-dev libeigen3-dev libgtest-dev
      - uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
          boost_version: 1.80.0
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'default'
          testPreset: 'default'
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'build/junitreport.xml'
      - run: cat build/Testing/Temporary/LastTest.log
      - name: Upload files
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: data
          path: ./build/data/

  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '17'
      - uses: lukka/get-cmake@latest
      - run: sudo apt-get install libcli11-dev libeigen3-dev
      - uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
          boost_version: 1.80.0
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default-with-lint'
          buildPreset: 'default-with-lint'
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
