name: Build and run
on: [push, pull_request]

permissions:
    checks: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - run: sudo apt-get install libcxxopts-dev libeigen3-dev
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: 'default'
          buildPreset: 'default'
          testPreset: 'default'
      - uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'build/junitreport.xml'
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: data
          path: ./build/data/
